actors:
  alice:
    image_url: /images/actors/alice.png
    name: alice
    url: http://sns.example.com/alice
  bob:
    image_url: /images/actors/bob.png
    name: bob
    url: http://sns.example.com/bob
  red:
    image_url: /images/actors/red.jpg
    name: れっど
    url: https://twitter.com/aruaru6161
author: red
description: 色々な話をします。
description_long: ファッション、恋愛、ITなどの話をするPodcastです。
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: れっどのPodcast
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: れっどのPodcast
url: https://aruaru6161.github.io
